openapi: "3.0.2"
info:
  title: Digital Bank API
  version: "1.0"
  description: API for managing banking operations for a digital bank. STD22036 & STD22047 & STD22086
servers:
  - url: http://localhost:8080

tags:
  - name: Banks
  - name: Categories
  - name: Accounts
  - name: BankSolds
  - name: HistoryBankSolds
  - name: Transactions
  - name: TransactionsHistories
  - name: Transfers
  - name: InterestValid
  - name: istoryInterests
  - name: InterestNotValid
  - name: LoanValid
  - name: HistoryLoans
  - name: LoanNotValid

paths:
  /banks:
    get:
      tags:
        - Banks
      summary: Retrieve list of banks
      description: Retrieve a list of all banks in the wallet app, optionally filtered by bank.
      operationId: getBanks
      responses:
        '200':
          description: List of banks retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '404':
          description: bank not found
        '500':
          description: Internal server error
  
  /banks/create:
    post:
      tags:
        - Banks
      summary: Create a new bank
      operationId: createBank
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
      responses:
        '200':
          description: Bank created successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /banks/update:
    put:
      tags:
        - Banks
      summary: Update banks
      description: edit bank items.
      operationId: updateBank
      parameters:
        - name: id 
          in: path
          description: Id that needs to be update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent bank
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
      responses:
        '200':
          description: modification successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request
        '403':
          description: Invalid account supplied
        '404':
          description: account not found
        '500': 
          description:  Internal server error

  /banks/{id}:
    get:
      tags:
        - Banks
      summary: Retrieve one of banks by id
      description: Retrieve only one of all banks in the wallet app, optionally filtered by bank.
      operationId: getBankById
      parameters:
        - name: id 
          in: path
          description: The id that needs to be retrieved
          required: true
          schema:
            type: string
      responses:
        '200':
          description: id of banks retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '404':
          description: bank not found
        '500':
          description: Internal server error


    delete:
      tags:
        - Banks
      summary: Delete a bank by id
      description: You can only delete one bank using the ID
      operationId: deleteBank
      parameters:
        - name: id 
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delete bank successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '404':
          description: bank not found
        '500':
          description: Internal server error
components:
  schemas:
    Bank:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
        email:
          type: string
          format: email

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
            - ENTREE
            - SORTIE

    BankSold:
      type: object
      properties:
        id:
          type: integer
          format: int64
        value:
          type: number
          format: float

    HistoryBankSold:
      type: object
      properties:
        id:
          type: integer
          format: int64
        value:
          type: number
          format: float
        bank_sold_date:
          type: string
          format: date

    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        password:
          type: string
        last_name:
          type: string
        first_name:
          type: string
        email:
          type: string
          format: email
        birthday:
          type: string
          format: date
        balance:
          type: number
          format: float
        net_monthly_salary:
          type: number
          format: float
        account_number:
          type: string
        overdraft_enabled:
          type: boolean
        creation_date:
          type: string
          format: date
        last_withdrawal_date:
          type: string
          format: date
        bank_solds_id:
          type: integer
          format: int64

    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        reason:
          type: string
        transaction_type:
          type: string
        category_id:
          type: integer
          format: int64
        comment:
          type: string

    TransactionHistory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        transaction_id:
          type: integer
          format: int64
        operation_date:
          type: string
          format: date-time

    Transfer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sender_account_id:
          type: integer
          format: int64
        receiver_account_id:
          type: integer
          format: int64
        bank_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        reason:
          type: string
        effective_date:
          type: string
          format: date-time
        status:
          type: string
        reference:
          type: string

    InterestValid:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        interest_rate:
          type: number
          format: float
        interest_date:
          type: string
          format: date

    HistoryInterest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        interest_rate:
          type: number
          format: float
        interest_date:
          type: string
          format: date

    InterestNotValid:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        interest_rate:
          type: number
          format: float
        interest_date:
          type: string
          format: date

    LoanValid:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        loans_date:
          type: string
          format: date
        status:
          type: integer
          enum:
            - 0
            - 100

    HistoryLoan:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        loans_date:
          type: string
          format: date
        status:
          type: integer
          enum:
            - 0
            - 100

    LoanNotValid:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: float
        loans_date:
          type: string
          format: date


  